
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMAND OPTION SPACE STRINGcommand : COMMAND SPACE OPTION SPACE STRINGcommand : COMMAND SPACE OPTION SPACE STRING SPACE'
    
_lr_action_items = {'COMMAND':([0,],[2,]),'$end':([1,6,7,],[0,-1,-2,]),'SPACE':([2,4,6,],[3,5,7,]),'OPTION':([3,],[4,]),'STRING':([5,],[6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'command':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> command","S'",1,None,None,None),
  ('command -> COMMAND SPACE OPTION SPACE STRING','command',5,'p_command','compilador.py',35),
  ('command -> COMMAND SPACE OPTION SPACE STRING SPACE','command',6,'p_command_error','compilador.py',45),
]
