
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CAMPEON_MUNDIAL CANTIDAD_VICTORIAS ESTADISTICAS_MUNDIAL GOLES_CONTRA ID JUGADORES_PAIS LISTAR_GOLES LISTAR_PARTIDOS MUNDIAL PROMEDIO_GOLES STRING TOTAL_GOLESmundial : MUNDIAL opcionopcion : LISTAR_PARTIDOS STRING\n              | LISTAR_GOLES STRING\n              | ESTADISTICAS_MUNDIAL STRING\n              | JUGADORES_PAIS STRING\n              | CANTIDAD_VICTORIAS STRING\n              | TOTAL_GOLES STRING\n              | CAMPEON_MUNDIAL STRING\n              | PROMEDIO_GOLES STRING\n              | GOLES_CONTRA STRING'
    
_lr_action_items = {'MUNDIAL':([0,],[2,]),'$end':([1,3,13,14,15,16,17,18,19,20,21,],[0,-1,-2,-3,-4,-5,-6,-7,-8,-9,-10,]),'LISTAR_PARTIDOS':([2,],[4,]),'LISTAR_GOLES':([2,],[5,]),'ESTADISTICAS_MUNDIAL':([2,],[6,]),'JUGADORES_PAIS':([2,],[7,]),'CANTIDAD_VICTORIAS':([2,],[8,]),'TOTAL_GOLES':([2,],[9,]),'CAMPEON_MUNDIAL':([2,],[10,]),'PROMEDIO_GOLES':([2,],[11,]),'GOLES_CONTRA':([2,],[12,]),'STRING':([4,5,6,7,8,9,10,11,12,],[13,14,15,16,17,18,19,20,21,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'mundial':([0,],[1,]),'opcion':([2,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> mundial","S'",1,None,None,None),
  ('mundial -> MUNDIAL opcion','mundial',2,'p_mundial','compilador.py',40),
  ('opcion -> LISTAR_PARTIDOS STRING','opcion',2,'p_opcion','compilador.py',44),
  ('opcion -> LISTAR_GOLES STRING','opcion',2,'p_opcion','compilador.py',45),
  ('opcion -> ESTADISTICAS_MUNDIAL STRING','opcion',2,'p_opcion','compilador.py',46),
  ('opcion -> JUGADORES_PAIS STRING','opcion',2,'p_opcion','compilador.py',47),
  ('opcion -> CANTIDAD_VICTORIAS STRING','opcion',2,'p_opcion','compilador.py',48),
  ('opcion -> TOTAL_GOLES STRING','opcion',2,'p_opcion','compilador.py',49),
  ('opcion -> CAMPEON_MUNDIAL STRING','opcion',2,'p_opcion','compilador.py',50),
  ('opcion -> PROMEDIO_GOLES STRING','opcion',2,'p_opcion','compilador.py',51),
  ('opcion -> GOLES_CONTRA STRING','opcion',2,'p_opcion','compilador.py',52),
]
